# Generated by Django 5.1.1 on 2024-09-18 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisgehc', '0006_remove_evento_limiteinscricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='local',
            field=models.CharField(default='Uece', max_length=50),
        ),
    ]
